<!-- Set the CHARACTER ENCODING for HTML to UTF-8 (Firefox Complains if not set) -->
<meta name="charset"            content="UTF-8"/>

<!-- Set some other standard META DATA for project -->
<meta http-equiv="Content-Type" content="text/html; utf-8"/>
<meta name="author"             content="${app.website.author.company} - ${app.website.author.name}: ${app.website.author.email}"/>
<meta name="description"        content="${app.seo.description}"/>

<!-- The VIEWPORT is set to allow for responsive MEDIA QUERIES -->
<meta name="viewport"  content="width=device-width, initial-scale=1"/>

<!-- Specify generator (FRAMEWORK) used -->
<meta name="generator" content="${app.website.generator}"/>
<meta name="keywords"  content="${app.seo.keywords}"/>

<!-- Set the THEME COLOR fir this project -->
<meta name="theme-color" content="dark"/>

<!-- Set project FAVICON -->
<link
    href="${env.project.assets.url}images/webAlly_logo_circle.png"
    rel="icon"
    type="image/png"/>