<?php
return [
    'color.red.' => (object)    [
        'bg'    => '#ff8a8',
        'text'  => colorDarken('#ff8a8',1),
        'hover' => colorDarken('#ff8a8',3)
    ],
    'color.orange' => (object)[
        'bg' => '#ffd180',
        'text'  => colorDarken('#ffd180',1),
        'hover' => colorDarken('#ffd180',3)
    ],
    'color.darkOrange' => (object)[
        'bg' => '#FC880F',
        'text'  => colorDarken('#FC880F',1),
        'hover' => colorDarken('#FC880F',3)
    ],
    'color.green' => (object)[
        'bg' => '#ccff90',
        'text'  => colorDarken('#ccff90',1),
        'hover' => colorDarken('#ccff90',3)
    ],
    'color.darkGreen' => (object)[
        'bg' => '#0b7a28',
        'text'  => colorDarken('#0b7a28',1),
        'hover' => colorDarken('#0b7a28',3)
    ],
    'color.teal' => (object)[
        'bg' => '#a7ffeb',
        'text'  => colorDarken('#a7ffeb',1),
        'hover' => colorDarken('#a7ffeb',3)
    ],
    'color.blue' => (object)[
        'bg' => '#80d8ff',
        'text'  => colorDarken('#80d8ff',1),
        'hover' => colorDarken('#80d8ff',3),
    ],

    'color.darkBlue' => (object)[
        'bg' => '#82b1ff',
        'text'  => colorDarken('#82b1ff',1),
        'hover' => colorDarken('#82b1ff',3)
    ],
    'color.purple' => (object)[
        'bg' => '#b388ff',
        'text'  => colorDarken('#b388ff',1),
        'hover' => colorDarken('#b388ff',3)
    ],
    'color.pink' => (object)[
        'bg' => '#f8bbd0',
        'text'  => colorDarken('#f8bbd0',1),
        'hover' => colorDarken('#f8bbd0',3)
    ],
    /*
    'color.brown' => (object)[
        'bg' => '#d7ccc8',
        'text'  => colorDarken('#d7ccc8',1),
        'hover' => colorDarken('#d7ccc8',3)
    ],*/
    'color.gray' => (object)[
        'bg' => '#cfd8dc',
        'text'  => colorDarken('#cfd8dc',1),
        'hover' => colorDarken('#cfd8dc',3)
    ],
    'color.darkGray' => (object)[
        'bg' => '#878788',
        'text'  => colorDarken('#878788',1),
        'hover' => colorDarken('#878788',3)
    ],
    'icon' => [
        'heepp-mail-envelope' => 'mail-envelope',
        'heepp-mail-envelope-open' => 'mail-envelope-open',
        'heepp-mail-envelope-closed' => 'mail-envelope-closed',
        'heepp-mail-error' => 'mail-error',
        'heepp-mail-checked' => 'mail-checked',
        'heepp-flag' => 'flag',
        'heepp-bookmark' => 'bookmark',
        'heepp-eye' => 'eye',
        'heepp-star' => 'star',
        'heepp-key' => 'key',
        'heepp-trash-can' => 'trash-can',
        'heepp-book-bookmark' => 'book-bookmark',
        'heepp-clipboard-edit' => 'clipboard-edit',
        'heepp-clipboard-text' => 'clipboard-text',
        'heepp-clipboard-list' => 'clipboard-list',
        'heepp-note' => 'note',
        'heepp-note-text' => 'note-text',
        'heepp-note-list' => 'note-list',
        'heepp-note-checked' => 'note-checked',
        'heepp-notebook' => 'notebook',
        'heepp-folders' => 'folders',
        'heepp-search' => 'search',
        'heepp-lock' => 'lock',
        'heepp-lock-open' => 'lock-open',
        'heepp-cloud' => 'cloud',
        'heepp-certificate' => 'certificate',
        'heepp-tags' => 'tags',
        'heepp-trophy' => 'trophy',
        'heepp-medal' => 'medal',
        'heepp-stop-watch' => 'stop-watch',
        'heepp-move' => 'move',
        'heepp-target-arrow' => 'target-arrow',
        'heepp-sun' => 'sun',
        'heepp-rainbow' => 'rainbow',
        'heepp-lightning' => 'lightning',
        'heepp-smiling-face' => 'smiling-face',
        'heepp-sad-face3' => 'sad-face3',
        'heepp-thumb-up' => 'thumb-up',
        'heepp-thumb-down' => 'thumb-down',
        'heepp-adobeacrobatreader' => 'adobeacrobatreader',
        'heepp-bitbucket' => 'bitbucket',
        'heepp-codeschool' => 'codeschool',
        'heepp-dropbox' => 'dropbox',
        'heepp-git' => 'git',
        'heepp-google' => 'google',
        'heepp-googledrive' => 'googledrive',
        'heepp-gulp' => 'gulp',
        'heepp-html5' => 'html5',
        'heepp-javascript' => 'javascript',
        'heepp-laravel' => 'laravel',
        'heepp-linux' => 'linux',
        'heepp-microsoftonenote' => 'microsoftonenote',
        'heepp-minutemailer' => 'minutemailer',
        'heepp-mysql' => 'mysql',
        'heepp-onedrive' => 'onedrive',
        'heepp-php' => 'php',
        'heepp-python' => 'python',
        'heepp-rails' => 'rails',
        'heepp-redis' => 'redis',
        'heepp-superuser' => 'superuser',
        'heepp-toggl' => 'toggl',
        'heepp-trello' => 'trello',
        'heepp-xcode' => 'xcode',
        'heepp-windows' => 'windows',
        'heepp-whatsapp' => 'whatsapp',
        'heepp-webpack' => 'webpack',
        'heepp-webstorm' => 'webstorm',
        'heepp-visualstudiocode' => 'visualstudiocode',
        'heepp-uikit' => 'uikit',
        'heepp-twitter' => 'twitter',
        'heepp-sublimetext' => 'sublimetext',
        'heepp-stackoverflow' => 'stackoverflow',
        'heepp-slack' => 'slack',
        'heepp-nginx' => 'nginx',
        'heepp-npm' => 'npm',
        'heepp-microsoftword' => 'microsoftword',
        'heepp-microsoft' => 'microsoft',
        'heepp-magento' => 'magento',
        'heepp-koding' => 'koding',
        'heepp-intel' => 'intel',
        'heepp-googlehangouts' => 'googlehangouts',
        'heepp-googlechrome' => 'googlechrome',
        'heepp-gmail' => 'gmail',
        'heepp-github' => 'github',
        'heepp-flickr' => 'flickr',
        'heepp-codio' => 'codio',
        'heepp-cakephp' => 'cakephp',
        'heepp-codepen' => 'codepen',
        'heepp-buffer' => 'buffer',
        'heepp-bitcoin' => 'bitcoin',
        'heepp-atom' => 'atom',
        'heepp-angular' => 'angular',
        'heepp-android' => 'android',
        'heepp-adobephotoshop' => 'adobephotoshop',
        'heepp-adobe' => 'adobe',
        'heepp-aboutme' => 'aboutme',
        'heepp-file-doc' => 'file-doc',
        'heepp-file-xls' => 'file-xls',
        'heepp-document-file-xml' => 'document-file-xml',
        'heepp-document-file-xls' => 'document-file-xls',
        'heepp-document-file-sql' => 'document-file-sql',
        'heepp-document-file-php' => 'document-file-php',
        'heepp-document-file-css' => 'document-file-css',
        'heepp-document-file-html' => 'document-file-html',
        'heepp-document-file-jpg' => 'document-file-jpg',
        'heepp-document-file-png' => 'document-file-png',
        'heepp-document-file-pdf' => 'document-file-pdf',
        'heepp-file-gif' => 'file-gif',
        'heepp-file-zip' => 'file-zip',
        'heepp-file-sql' => 'file-sql',
        'heepp-file-psd' => 'file-psd',
        'heepp-file-css' => 'file-css',
        'heepp-file-html' => 'file-html',
        'heepp-file-jpg' => 'file-jpg',
        'heepp-file-png' => 'file-png',
        'heepp-file-pdf' => 'file-pdf',
        'heepp-file-app' => 'file-app'
    ],
];
